name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build ChatServer
    - name: Build Test
      run: dotnet build ChatServerTests
    - name: Test with the dotnet CLI
      run: dotnet test 
